#Build-Settings
markdown: kramdown
permalink: pretty
exclude: ['README.md', 'README.md.orig', 'LICENSE.txt', 'CNAME']
url: "https://alaoweb.github.io/2020.alaoweb.org"
plugins:
- jekyll-sitemap
safe: false

#Google-Analytics & API Key
googleAnalyticsTrackingId: "UA-101881286-2"
googleAnalyticsSiteUrl: "2020.alaoweb.org"
siteVerification: "2dvmkAUuRuFhMopsqIvEBr1-YCYHb9v2Py9FEsrUg40"
googleMapsApiKey: "AIzaSyDUQZ2d8zeEcwzJur9Av9KSg2l1W1NNaH8"

#Head
metaKeywords: "event, alao, academic, libraries, ohio"
twitterAccount: "@ALAOorg"
socialImageSrcTwitter: "/img/seo/sharing-twitter.png"
socialImageSrcFacebook: "/img/seo/sharing-facebook.png"


#Organizer-Info
organizerName: "ALAO"
organizerAlternateName: "Academic Library Association of Ohio"
organizerDescription: "ALAO of the Ohio chapter of ACRL"
organizerEmail: "2021-cpc@alaoweb.org"
organizerLogo: "/img/seo/organizer-logo.svg"
organizerLink: "https://www.alaoweb.org/"

#Site-Settings
title: "ALAO Virtual Conference 2020"
email: "2021-cpc@alaoweb.org"
description: "Virtual Conference"
permalink: "/posters/:title"
#############################################################################


# -------------------------------------------------------------
# About Block
# -------------------------------------------------------------
aboutTitle: "ALAO Virtual Conference"
aboutBlock:
 - {title: "Sessions", image: "sessions.jpg", text: "Prerecorded traditional presentations with live Q&A" }
 - {title: "Pre-Conferences", image: "preconference.jpg", text: "An opportunity for a deeper dive into a single topic in a workshop format" }
 - {title: "Posters", image: "posters.jpg", text: "Short videos with asynchronous, text-based Q&A" }
 - {title: "Networking", image: "networking.jpg", text: "Opportunities to connect with other attendees in a less formal structure"}

# -------------------------------------------------------------
# Awards
# -------------------------------------------------------------
showAwardWinners: true
awardAnnouncementTime: "2020-10-29T12:10:00"

# -------------------------------------------------------------
# Call For Proposals & Sponsors
# -------------------------------------------------------------
c4speakersEnable: false
c4pUrl: "https://docs.google.com/forms/d/e/1FAIpQLSdfGZEuGcn_KmpEqd9-GgU-xPWhViP1bivXOvJKcEvJ1DtLFw/viewform?usp=sf_link"
speakersC4pButton: "Become a speaker"

c4sponsorsEnable: false
c4sponsorsUrl: "/handouts/sponsorship_letter_2020.pdf"
sponsorsC4sponsorsButton: "Become a sponsor"

# -------------------------------------------------------------
# Code of Conduct - Contact Info
# -------------------------------------------------------------
codContactName: ALAO President
codContactEmail: president@alaoweb.org

# -------------------------------------------------------------
# Footer
# -------------------------------------------------------------
conferenceYear: 2020

socialLinks:
 - {link: "https://twitter.com/ALAOorg", icon: "twitter", title: "Twitter"}
 - {link: "https://www.facebook.com/ALAOorg", icon: "facebook", title: "Facebook"}

footerBlocks:
 - title: "Links"
   links:
     - {link: "https://www.alaoweb.org", text: "ALAO Website", featured: true }
 - title: "Contacts"
   links:
     - {link: "mailto:2021-cpc@alaoweb.org", text: "2021-cpc@alaoweb.org"}
 - title: "Code of Conduct"
   links:
     - {permalink: "/cod/", text: "Code of Conduct"}

# -------------------------------------------------------------
# Hero Block - Main Section
# -------------------------------------------------------------
heroTitle: "Building Bridges: Dialogue, Deliberation & Connection in Academic Libraries"
heroImage: "bridges_conference_logo_fixed.svg"
eventDate: "October 27-29, 2021"
typeoutEnable: false
typeoutTextValues: '"", ""'
typeoutFallback: "Building Bridges"

# Call to Action Buttons
heroButtons:
  # - {permalink: "/#tickets", text: "Register"}
  # - {permalink: "/awards", text: "View Award Winners" }
  # - {link: "https://forms.gle/DWoBhvAnJDDiR3tv6", text: "Apply for Scholarship"}
  # - {link: "https://docs.google.com/forms/d/e/1FAIpQLSdfGZEuGcn_KmpEqd9-GgU-xPWhViP1bivXOvJKcEvJ1DtLFw/viewform", text: "Become a speaker"}

# -------------------------------------------------------------
# Latest News Block
# -------------------------------------------------------------
latestNewsEnable: false
latestNewsTitle: "Latest news"

# -------------------------------------------------------------
# Location Block
# -------------------------------------------------------------
locationBlockEnable: false
locationBlockTitle: "Location"
eventLocationName: "Nationwide Hotel and Conference Center"
eventLocationLink: "https://www.nwhotelandconferencecenter.com/"
eventStreetAddress: "100 Green Meadows Drive"
eventAddressLocality: "Columbus"
eventAddressLocalityRegion: "Ohio"
eventPostalCode: "43035"
eventAddressCountry: "United States"
eventStartTime: "2020-10-26T10:00" # 2020-10-26T10:00
eventDoorTime: "09:00"
eventEndTime: "2020-10-28T17:00"
eventPlaceCoordinates: "40.154830, -83.016290"
mapCenterCoordinates: "40.154830, -83.016290"
mapMobileCenterCoordinates: "40.154830, -83.016290"

# -------------------------------------------------------------
# Logistics Find Way Block
# -------------------------------------------------------------
findWayTitle: "Find your way here"
findWayDistance: "Distance"
findWayDriving: "DRIVING"
findWayWalking: "WALKING"
findWayBicycling: "BICYCLING"
findWayTransit: "TRANSIT"
findWayFindFlight: "Find Flight"
logisticsMapCenterCoordinates: "40.154830, -83.016290"
logisticsMapMobileCenterCoordinates: "40.154830, -83.016290"
logisticsMapAutoDirections: false

# Logistics Direction Details Block
directionDetailsImage: "columbus-skyline.jpg"
directionDetailsTitle: "Get around Columbus"
directionDetailsCards:
 - {title: "From the Airport", information: 'Airport is just outside of the city center. The conference center is easily reachable by a 20 minute car ride. More information is available at <a href="https://flycolumbus.com/">airport website</a>.'}
 - {title: "Public Transit", information: 'Bus route 102 travels from city center to Nationwide Hotel & Conference Center in about 1 hour. More information on the <a href="https://www.cota.com/">COTA website</a>'}
 - {title: "Hotels", information: 'Columbus has lots of great accommodations. Nationwide also has an <a href="https://www.nwhotelandconferencecenter.com/">on-site hotel</a> with five-star luxury and the business-class services.'}
directionDetailsWideCards:
 - title: "THINGS TO DO IN AND AROUND COLUMBUS"
   subCards:
     - title: "Neighborhoods"
       links:
         - {link: "https://shortnorth.org/", text: "Short North"}
         - {link: "https://germanvillage.com/", text: "German Village"}
     - title: "Art & Culture"
       links:
         - {link: "https://wexarts.org/", text: "Wexner Center for the Arts"}
         - {link: "https://www.columbusmuseum.org/", text: "Columbus Museum of Art"}
         - {link: "http://www.thurberhouse.org/", text: "Thurber House"}
     - title: "Entertainment & Shopping"
       links:
         - {link: "https://polarisfashionplace.com/", text: "Polaris Fashion Place"}
         - {link: "https://www.starlanespolaris.com/", text: "Star Lanes Bowling"}

# -------------------------------------------------------------
# Navigation
# -------------------------------------------------------------
navigationLinks:
 - {permalink: "/", text: "Home"}
 - {permalink: "/preconference/", text: "Preconferences"}
 - {permalink: "/schedule/", text: "Schedule"}
 - {permalink: "/speakers/", text: "Speakers"}
 - {permalink: "/posters/", text: "Posters"}
 - {permalink: "/team/", text: "Team"}
 - {permalink: "/awards/", text: "Awards"}
# - {permalink: "/lodging/", text: "Lodging"}

#bottomNavigationLinks:
# - {link: "https://bit.ly/dfua-c4p", text: "Become a speaker"}
#rightNavigationButtons:
# - {link: "https://bit.ly/dfua-c4p", text: "Become a speaker"}

# -------------------------------------------------------------
# Organizers & Partners/Sponsors Block
# -------------------------------------------------------------
organizersEnable: False
organizersTitle: "Organizers"
sponsorsEnable: True
sponsorsTitle: "Conference Sponsors"

# -------------------------------------------------------------
# Posters
# -------------------------------------------------------------
postersTitle: "POSTER SESSIONS"
postersBackground: waves-background.svg
showPosters: true
noPostersText: "Posters Forthcoming"
postersCommentsEnabled: true
discusShortName: "alaoweb"
showPosterVoting: true
posterVotingLink: "https://docs.google.com/forms/d/e/1FAIpQLSfas6Fj3iaA20Ma6GwHoRjKubYWRQS14ZQ6pL_58RSEmXcnUw/viewform"

# -------------------------------------------------------------
# Preconference
# -------------------------------------------------------------
preconferenceTitle: "Preconference"
enablePreconference: True

# Preconference About Block
aboutPreconferenceTitle: "Meet our Speakers"
aboutPreconferenceTitleShow: False
preconferenceRows:
 - {title: "Renewal: Promoting Civility and Self-Care in (Academic) Libraries",
    image: "kaetrena_kendrick.jpg",
    details: "The Renewal Seminar offers a pathway for individuals to increase their awareness of the associated
frameworks, development, outcomes, and emerging countermeasures of low morale, which is defined
as repeated and protracted exposure to workplace abuse and neglect (Kendrick, 2017). Learning more
about these concerns can help promote authentic civility and collegiality in North American libraries and
reduce the factors that can cause employee mistreatment and misconduct in library workplaces.",
    list: "
      Through pre-assessments and reflections and on-site participation in targeted discussions, Seminar attendees will be able to:<br/>
      <ul>
        <li><p>Understand the development the low morale experience;<p></li>
        <li><p>Evaluate the role of Library and Information Science (LIS)-based and workplace barriers to resolving low morale;</p></li>
        <li><p>Identify and consider leadership behaviors that decrease low morale in workplace environments; and</p></li>
        <li><p>Create and engage with a collegial community to increase best practices in applying workplace civility, honing humane leadership skills, and encouraging self-advocacy.</p></li>
      </ul>"
 }
 - {title: "From Being To Doing: Anti-racism as Action at Work",
      image: "ione_damasco.png",
      details: "Over the past few years, the conversation around equity in libraries has focused on thinking of the word ally as a verb, rather than as an identity. With recent events highlighting specific issues around race, the conversation has now shifted to many people wanting to be anti-racist. In this session, we will focus on anti-racism as action, rather than using the word anti-racist as identity. In particular, we will examine our notions of professionalism in libraries. Can changing how we define professionalism in library workplaces be an example of anti-racist action? We will take a critical look at how certain hallmarks of white supremacist culture inform our notions of professionalism and acceptable workplace culture. These commonly accepted traits can actually contribute to low morale, the prevalence of microaggressions, retention issues, etc. Together, we will explore ways to transform our workplace cultures by looking at specific actions that resist these hallmarks in order to create equitable workplaces.",
      list: ""
 }

# Preconference Location Block
preconferenceLocationEnable: False
preconferenceLocationBlockTitle: "Location"
preconferenceLocationName: "Nationwide Hotel & Conference Center"
preconferenceLocationLink: "https://www.nwhotelandconferencecenter.com/"
preconferenceStreetAddress: "100 Green Meadows Drive"
preconferenceAddressLocality: "Lewis Center"
preconferenceAddressLocalityRegion: "Ohio"
preconferencePostalCode: "43035"
preconferenceAddressCountry: "United States"
preconferenceTimeTitle: "Preconference through"
preconferenceStartTime: "2020-01-01T10:00"
preconferenceDoorTime: "09:00"
preconferenceEndTime: "2020-10-30T00:00"
viewOnMap: "View on Google Maps"
preconferencePlaceCoordinates: "40.154830, -83.016290"
preconferenceMapCenterCoordinates: "40.154830, -83.016290"
preconferenceMapMobileCenterCoordinates: "40.154830, -83.016290"

# -------------------------------------------------------------
# Rockstar Speakers Block
# -------------------------------------------------------------
rockstarSpeakersEnable: true
rockstarSpeakersImage: "featured-speakers.jpg"
rockstarSpeakersCount: 3
rockstarSpeakersTitle: "Featured Speakers"
rockstarSpeakersButtonText: "See all speakers"

# -------------------------------------------------------------
# Service Project Block
# -------------------------------------------------------------
# this still 2020
serviceprojectTitle: ""
serviceprojectImage: dfs_logo.jpg
serviceprojectInfo: 'Each year for the ALAO conference we host a service project to collect materials for a charitable organization. This year, we are partnering with Dress for Success, an organization that serves women by providing clothes and other tools to seek economic independence. However, instead of collecting clothes at the conference, we ask that you consider making a donation to this worthy organization. There are three affiliates of Dress for Success in Ohio, and you can choose the region that you would like to support.  If you decide to make a donation, please put ALAO member in the notes field.'
serviceprojectLocations:
  cleveland:
    url: "https://cleveland.dressforsuccess.org/get-involved/donate/"
  columbus:
    url: "https://columbus.dressforsuccess.org/get-involved/donate/"
  cincinnati:
    url: "https://cincinnati.dressforsuccess.org/get-involved/donate/"


# -------------------------------------------------------------
# Speakers List Block
# -------------------------------------------------------------
showSessions: true

# -------------------------------------------------------------
# Statistic Block
# -------------------------------------------------------------
statisticBlockEnable: false
statisticBlockImage: "data.jpg"
statisticBlock:
 - {count: "200", specialCharacter: "+", info: "attendees", detail: "on average"}
 - {count: "20", specialCharacter: "+", info: "hours", detail: "of high-quality content"}
 - {count: "20", specialCharacter: "+", info: "speakers", detail: "from ohio and beyond"}
 - {count: "2", specialCharacter: "", info: "parallel tracks", detail: "plus two pre-conferences"}

# -------------------------------------------------------------
# Subscribe Block
# -------------------------------------------------------------
subscribeEnable: true
subscribeImage: "speak-up.jpg"
subscribeTitle: "Subscribe to ALAO Mailing List"
subscribeAction: "https://alaoweb.us10.list-manage.com/subscribe/post?u=ac241e268ddc3495466be87a8&amp;id=685009e39b"
subscribeInfo: "Stay Informed of ALAO Events!"

# -------------------------------------------------------------
# Surveys
# -------------------------------------------------------------
sessionFeedbackForm: "https://docs.google.com/forms/d/e/1FAIpQLSdVgEk_d_Ed4mt7lBNZQx2XzT9fP1C7a5KFME1vyToYB8NDFA/viewform?usp=pp_url"
sessionFeedbackParameter: "entry.1153076421"
preconferenceWorkshopFeedbackForm: "https://docs.google.com/forms/d/e/1FAIpQLScr9oiR9VEgU77lISo2YV_MkrC3SK-D_7ixZ14UYr9L4AWz0w/viewform"
preconferenceFeedbackForm: "https://docs.google.com/forms/d/e/1FAIpQLScrp2h3Of9-7skigJ3H8-r9R51we8bVZOCj2D1eMY6hhGFh_Q/viewform"
keynoteFeedbackForm: "https://docs.google.com/forms/d/e/1FAIpQLSdAuGKiH8bP95KnrvQQarT8_hEOFp_XO3YHFHwlVwDwFuTFAQ/viewform"

# -------------------------------------------------------------
# Team Block
# -------------------------------------------------------------
teamBlockTitle: "About us"
aboutUs: "The Academic Library Association of Ohio (ALAO) is a chapter of the Association of College and Research Libraries (ACRL). ALAO exists to develop, promote, and improve library and information services in Ohioâ€™s higher education community, to advance the interests of academic librarianship and the personnel of academic libraries, and to provide leadership and advocacy for the educational and policy concerns of the academic library community in Ohio."
showOrganizers: True
showProgramCommittee: False

# -------------------------------------------------------------
# Tickets Block
# -------------------------------------------------------------
ticketsHorizontalEnable: false
ticketsVerticalEnable: true
ticketsBuyButtonLink: "https://www.alaoweb.org/event-3712747"
ticketsBuyButtonText: "Register Now"
ticketsTitle: "Registration"
ticketsInfo: "Conference registration provides access to all keynotes, pre-recorded sessions, and posters. Pre-conference sessions are ticketed separately during registration"
ticketsOffers:
 - name: "Early Bird"
   price: "10-30"
   priceCurrency: "USD"
   ticketsNumber: "500"
   ribbon: "-25%"
   featured: true
   buyButtonLink: "https://www.alaoweb.org/event-3712747"
   buyButtonText: "Register Now"
   additionalInfo: ""
   ticketContentList: ["Keynotes", "Pre-recorded Sessions", "Posters"]
   validFrom: "2020-07-20"
   validThrough: "2020-09-28"
   disabled: true
   soldOut: false
   soldOutText: "Sold Out"

 - name: "Regular Rate"
   price: "30-50"
   priceCurrency: "USD"
   ticketsNumber: "500"
   ribbon:
   featured:
   buyButtonLink: "https://www.alaoweb.org/event-3712747"
   buyButtonText: "Register Now"
   additionalInfo: ""
   ticketContentList: ["Keynotes", "Pre-recorded Sessions", "Posters"]
   validFrom: "2020-09-29"
   validThrough: "2020-10-16"
   disabled: true
   soldOut: false
   soldOutText: "Sold Out"

 - name: "Renewal Preconference"
   price: "50"
   priceCurrency: "USD"
   ticketsNumber: "30"
   ribbon:
   featured:
   buyButtonLink: "https://www.alaoweb.org/event-3905631"
   buyButtonText: "Register Now"
   additionalInfo: ""
   ticketContentList: ["Preconference"]
   altSubtitle: "Separate Ticket Required"
   validFrom: ""
   validThrough: "2020-10-16"
   disabled: true
   soldOut: false
   soldOutText: "Sold Out"

 - name: "Anti-racism Preconference"
   price: "Free"
   priceCurrency: ""
   ticketsNumber: "500"
   ribbon:
   featured:
   buyButtonLink: "https://www.alaoweb.org/event-3913408"
   buyButtonText: "Register Now"
   additionalInfo: ""
   ticketContentList: ["Preconference"]
   altSubtitle: ""
   validFrom: ""
   validThrough: "2020-10-16"
   disabled: true
   soldOut: false
   soldOutText: "Sold Out"

# -------------------------------------------------------------
# Tweets Feed Block
# -------------------------------------------------------------
tweetsFeedEnable: true
tweetsFeedImage: "katy.jpg"
tweetsFeedTitle: "What's Up?"
twitterHashTag: "2021alao"
twitterFeed: "https://twitter.com/ALAOorg"

# -------------------------------------------------------------
# Venue Block
# -------------------------------------------------------------
venueBlockEnable: false
venueBlockTitle: "Venue"
venueBigImage: "venue_0.jpg"
venueSmallImage1: "venue_1.jpg"
venueSmallImage2: "venue_2.jpg"
venueSmallImage3: "venue_3.jpg"
venueTitle: "Nationwide Hotel & Conference Center"
venueFeatures: ["Free Parking", "Wi-Fi Accessible Property-wide"]
